import { ReactNode } from 'react';
import './globals.css';

export const metadata = {
  title: 'Setup Next13 Tailwind ESlint Prettier and Vitest',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
